DIFFICULTY = {
    "fps": 2,
    "max_frames": 650,
    "rows": 5,
    "cols": 9,
    "initial_sun": 50,
    "natural_sun_production": 25,
    "natural_sun_cooldown": 5,
    "mowers": False,
    "survival_score": 0,
    "survival_step": 20,
    "alive_plant_score": 0,
    "alive_mower_score": 0,
}


ZOMBIE_SPAWN = {
    "first_wave_delay_sec": 18,
    "wave_interval_sec": 27,
    "post_clear_wave_delay_sec": 3,
    "flag_wave_followup_interval_sec": 50,
    "flag_wave_modulo": 10,
    "flag_wave_remainder": 9,
    "base_advanced_probability": 0.05,
    "advanced_probability_growth": 2.0,
    "max_advanced_probability": 1.0,
    "cone_probability_multiplier": 3.0,
}


REWARDS = {
    "zombie_kill": {
        "use_type_rewards": True,
        "default": 8.00,
        "zombie": 8.00,
        "flag": 12.00,
        "conehead": 12.00,
        "buckethead": 20.00,
    },
    "sun_collect": 0.01,
    "wave_complete": 20.0,
    "game_win": 50.0,
    "streak_bonus": 0.0,
    "survival_per_step": 0.0,
    "plant_sunflower": 0.10,
    "plant_attacker": 0.35,
    "plant_wall": 0.18,
    "plant_other": 0.30,
    "plant_lost": -0.25,
    "sunflower_lost": -0.80,
    "lawnmower_triggered": -50.0,
    "game_lose": -6.0,
    "invalid_action": -0.01,
    "wait_with_sun": -0.02,
    "wait_sun_threshold": 300,
    "coverage": {
        "scale": 0.0,
    },
    "proximity": {
        "scale": 0.0,
    },
    "potential": {
        "sun_scale": 0.06,
        "sun_cap": 300.0,
        "plant_scale": 0.22,
        "spread_bonus": 0.06,
        "lawnmower_scale": 0.35,
        "zombie_threat_scale": 0.35,
        "zombie_distance_bonus": 0.75,
        "wave_scale": 0.05,
        "delta_scale": 0.18,
    },
}


CURRICULUM = {
    "enabled": True,
    "strategy": "stage_gate",
    "default_burn_in": None,
    "default_stage_epsilon": {
        "start": 0.35,
        "end": 0.05,
        "decay_episodes": 20000,
    },
    "stage_gate": {
        "stages": [
            {
                "stage_name": "sim_pea_bootstrap_3rows",
                "enabled_rows": [0, 1, 2],
                "enabled_plants": [0],
                "initial_sun": 450,
                "target_frames": 320,
                "target_flag_waves": 0,
                "timeout_frames": 420,
                "min_episodes": 30,
                "mean_reward_threshold": 22.0,
                "mean_success_rate_threshold": 0.75,
                "epsilon": {
                    "start": 1.0,
                    "end": 0.05,
                    "decay_episodes": 20000,
                },
            },
            {
                "stage_name": "sim_sun_pea_economy_3rows",
                "enabled_rows": [0, 1, 2],
                "enabled_plants": [1, 0],
                "initial_sun": 50,
                "target_frames": 420,
                "target_flag_waves": 0,
                "timeout_frames": 560,
                "min_episodes": 500,
                "mean_reward_threshold": 80.0,
                "mean_success_rate_threshold": 0.80,
            },
            {
                "stage_name": "sim_wallnut_first_flag_3rows",
                "enabled_rows": [0, 1, 2],
                "enabled_plants": [1, 0, 3],
                "initial_sun": 150,
                "target_frames": 520,
                "target_flag_waves": 1,
                "timeout_frames": 800,
                "min_episodes": 1000,
                "mean_reward_threshold": 100.0,
                "mean_success_rate_threshold": 0.70,
            },
            {
                "stage_name": "sim_basic_defense_full_rows",
                "enabled_rows": [0, 1, 2, 3, 4],
                "enabled_plants": [1, 0, 3, 5],
                "initial_sun": 150,
                "target_frames": 600,
                "target_flag_waves": 1,
                "timeout_frames": 900,
                "min_episodes": 1000,
                "mean_reward_threshold": 90.0,
                "mean_success_rate_threshold": 0.55,
            },
            {
                "stage_name": "sim_instants_two_flags",
                "enabled_rows": [0, 1, 2, 3, 4],
                "enabled_plants": [1, 0, 3, 5, 7, 17, 2],
                "initial_sun": 150,
                "target_frames": 650,
                "target_flag_waves": 2,
                "timeout_frames": 1100,
                "min_episodes": 1000,
                "mean_reward_threshold": 110.0,
                "mean_success_rate_threshold": 0.60,
            },
            {
                "stage_name": "sim_pult_support_two_flags",
                "enabled_rows": [0, 1, 2, 3, 4],
                "enabled_plants": [1, 0, 3, 5, 7, 17, 2, 21, 34],
                "initial_sun": 100,
                "target_frames": 700,
                "target_flag_waves": 2,
                "timeout_frames": 1200,
                "min_episodes": 1000,
                "mean_reward_threshold": 120.0,
                "mean_success_rate_threshold": 0.50,
            },
            {
                "stage_name": "sim_full_deck_two_flags",
                "enabled_rows": [0, 1, 2, 3, 4],
                "enabled_plants": [1, 0, 5, 7, 3, 17, 2, 21, 34, 39],
                "initial_sun": 50,
                "target_frames": 750,
                "target_flag_waves": 2,
                "timeout_frames": 1300,
                "min_episodes": 1000,
                "mean_reward_threshold": 130.0,
                "mean_success_rate_threshold": 0.60,
            },
            {
                "stage_name": "sim_full_deck_three_flags",
                "enabled_rows": [0, 1, 2, 3, 4],
                "enabled_plants": [1, 0, 5, 7, 3, 17, 2, 21, 34, 39],
                "initial_sun": 50,
                "target_frames": 800,
                "target_flag_waves": 3,
                "timeout_frames": 1500,
                "min_episodes": 1000,
                "mean_reward_threshold": 140.0,
                "mean_success_rate_threshold": 0.50,
            },
        ],
    },
}
